In [97]:
from scipy import signal
from scipy.signal import freqs
import numpy as np  #Importa libreria numerica 
import sympy as sym #simbolica
import matplotlib.pyplot as plt #importa matplotlib solo pyplot

sym.init_printing() #activa a jupyter para mostrar simbolicamente el output
%matplotlib widget 

In [98]:
# Parametros de Entrada
FS=5000*10;
fp=[800, 1250]; #Banda de Paso [Hz]
fs=[200, 5000]; #Banda de Rechazo [Hz]
Wp=np.dot(2*np.pi,fp); #Banda de Paso [rad/s]
Ws=np.dot(2*np.pi,fs); #Banda de Rechazo [rad/s]
Ap=0.25; #Atenuacion maxima en Banda de Paso [dB]
As=30; #%Atenuacion minima en Banda de Rechazo [dB]


In [102]:
N, Wn = signal.cheb1ord(Wp, Ws, Ap, As, analog=True)
b, a = signal.cheby1(N, Ap, Wn, btype='bandpass', analog=True)
w, h = signal.freqs(b, a)

In [103]:
Filtro=signal.TransferFunction(b,a) #Funcion de transferencia calculada
#Implementacion como PasaAlto/PasaBajo
sos = signal.cheby1(N, Ap, Wn, btype='bandpass', output='sos', analog=True)
PasaBajo=signal.TransferFunction(2*sos[0,:3],sos[0,3:])
PasaAlto=signal.TransferFunction(1/2*sos[1,:3],sos[1,3:])

In [107]:
plt.figure()
plt.semilogx(w, 20 * np.log10(abs(h)))
plt.title('Chebyshev I ')
plt.xlabel('Frecuencia [rad/seg]')
plt.ylabel('Amplitud [dB]')
plt.grid(which='both', axis='both')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

TransferFunctionContinuous(
array([16420899.35090685,        0.        ,        0.        ]),
array([1.00000000e+00, 5.08000167e+03, 9.58572335e+07, 2.00550427e+11,
       1.55854546e+15]),
dt: None
)

In [132]:
PasaAlto

TransferFunctionContinuous(
array([0.5, 0. , 0. ]),
array([1.00000000e+00, 1.89557535e+03, 2.35000932e+07]),
dt: None
)

In [93]:
PasaBajo

TransferFunctionContinuous(
array([32841798.70181369,        0.        ,        0.        ]),
array([1.00000000e+00, 3.18442632e+03, 6.63208202e+07]),
dt: None
)